theme: minima
markdown: CommonMarkGhPages
title: Maksim Ramanouski
author: Maksim Ramanouski
description: >
  My homepage. Maksim Ramanouski aka maxromanovsky.
  Occasional blogging, basic info.
  Solutions Architect, metal lover, nerd, traveler, casual photographer, binge-watcher, newbie gamer.


show_excerpts: true
excerpt_separator: <!--more-->
permalink: /blog/:categories/:year-:month-:day-:title.html
highlighter: rouge

header_pages:
  - index.md
  - blog.md
  - about.md
disqus:
  shortname: maxromanovsky
google_analytics: UA-143359647-1

minima:
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%-d %b %Y"

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

twitter_username: maxromanovsky
github_username: maxromanovsky
facebook_username: max.romanovsky
instagram_username: maxromanovsky
linkedin_username: maxromanovsky
telegram_username: maxromanovsky
rss: rss

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-gist
  - jemoji

certificates:
  - name: AWS Certified Cloud Practitioner
    image: https://www.certmetrics.com/api/ob/image/amazon/c/9
    url: https://www.certmetrics.com/amazon/public/badge.aspx?i=9&t=c&d=2019-06-14&ci=AWS00823181
  - name: Google Cloud Professional Cloud Architect
    image: https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/11684198
    url: https://www.credential.net/1nwrodht
  - name: Google Cloud Professional Data Engineer
    image: https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/11667075
    url: https://www.credential.net/ctd7pqmw
