#title: Maksim Ramanouski personal page
theme: minima
title: Maksim Ramanouski
author: Maksim Ramanouski
description: >
  My homepage. Occasional blogging, basic info.

show_excerpts: true
excerpt_separator: <!--more-->
permalink: /blog/:year-:month-:day-:title.html
highlighter: rouge

header_pages:
  - index.md
  - about.md
disqus:
  shortname: maxromanovsky
google_analytics: UA-143359647-1

minima:
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%-d %b %Y"

  social_links:
    twitter: maxromanovsky
    github: maxromanovsky
    facebook: max.romanovsky
    instagram: maxromanovsky
    linkedin: maxromanovsky
    telegram: maxromanovsky
    rss: rss

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
